// Auto-generated from Zod schema
export type ValidPackageRulePath =
  "description" |
  "name" |
  "rules" |
  "rules.accommodationInfo" |
  "rules.accommodationInfo.accommodations" |
  "rules.accommodationInfo.accommodations[]._key" |
  "rules.accommodationInfo.accommodations[]._type" |
  "rules.accommodationInfo.accommodations[].accommodationType" |
  "rules.accommodationInfo.accommodations[].accommodationType._ref" |
  "rules.accommodationInfo.accommodations[].accommodationType._type" |
  "rules.accommodationInfo.accommodations[].accommodationType._weak" |
  "rules.accommodationInfo.accommodations[].additonalCost" |
  "rules.accommodationInfo.accommodations[].roomDetails" |
  "rules.accommodationInfo.accommodations[].roomDetails.locked" |
  "rules.accommodationInfo.accommodations[].roomDetails.value" |
  "rules.allowedVesselsForDeparture" |
  "rules.allowedVesselsForDeparture[]._key" |
  "rules.allowedVesselsForDeparture[]._ref" |
  "rules.allowedVesselsForDeparture[]._type" |
  "rules.allowedVesselsForDeparture[]._weak" |
  "rules.cabinInfo" |
  "rules.cabinInfo.cabins" |
  "rules.cabinInfo.cabins[]._key" |
  "rules.cabinInfo.cabins[]._type" |
  "rules.cabinInfo.cabins[].additonalCost" |
  "rules.cabinInfo.cabins[].cabinType" |
  "rules.cabinInfo.cabins[].cabinType._ref" |
  "rules.cabinInfo.cabins[].cabinType._type" |
  "rules.cabinInfo.cabins[].cabinType._weak" |
  "rules.cabinInfo.cabins[].isIncluded" |
  "rules.cabinInfo.inbound" |
  "rules.cabinInfo.inbound.cabinSuggestGroups" |
  "rules.cabinInfo.inbound.cabins" |
  "rules.cabinInfo.inbound.cabins[]._key" |
  "rules.cabinInfo.inbound.cabins[]._ref" |
  "rules.cabinInfo.inbound.cabins[]._type" |
  "rules.cabinInfo.inbound.cabins[]._weak" |
  "rules.cabinInfo.outbound" |
  "rules.cabinInfo.outbound.cabinSuggestGroups" |
  "rules.cabinInfo.outbound.cabins" |
  "rules.cabinInfo.outbound.cabins[]._key" |
  "rules.cabinInfo.outbound.cabins[]._ref" |
  "rules.cabinInfo.outbound.cabins[]._type" |
  "rules.cabinInfo.outbound.cabins[]._weak" |
  "rules.dates" |
  "rules.dates.inbound" |
  "rules.dates.inbound.date" |
  "rules.dates.inbound.locked" |
  "rules.dates.outbound" |
  "rules.dates.outbound.date" |
  "rules.dates.outbound.locked" |
  "rules.daysAshore" |
  "rules.journeyDuration" |
  "rules.journeyType" |
  "rules.packageCode" |
  "rules.personConfiguration" |
  "rules.personConfiguration.adults" |
  "rules.personConfiguration.adults.locked" |
  "rules.personConfiguration.adults.maxQuantity" |
  "rules.personConfiguration.adults.minQuantity" |
  "rules.personConfiguration.adults.preSelectedValue" |
  "rules.personConfiguration.children" |
  "rules.personConfiguration.children.locked" |
  "rules.personConfiguration.children.maxAge" |
  "rules.personConfiguration.children.maxQuantity" |
  "rules.personConfiguration.children.minAge" |
  "rules.personConfiguration.children.minQuantity" |
  "rules.personConfiguration.children.preSelectedValue" |
  "rules.personConfiguration.maxTotalTravelers" |
  "rules.personConfiguration.minTotalTravelers" |
  "rules.personConfiguration.roomQuantity" |
  "rules.personConfiguration.roomQuantity.locked" |
  "rules.personConfiguration.roomQuantity.maxQuantity" |
  "rules.personConfiguration.roomQuantity.minQuantity" |
  "rules.ports" |
  "rules.ports.allowDifferentReturn" |
  "rules.ports.availablePortsFrom" |
  "rules.ports.availablePortsFrom[]._key" |
  "rules.ports.availablePortsFrom[]._ref" |
  "rules.ports.availablePortsFrom[]._type" |
  "rules.ports.availablePortsFrom[]._weak" |
  "rules.ports.availablePortsTo" |
  "rules.ports.availablePortsTo[]._key" |
  "rules.ports.availablePortsTo[]._ref" |
  "rules.ports.availablePortsTo[]._type" |
  "rules.ports.availablePortsTo[]._weak" |
  "rules.ports.defaultPortFrom" |
  "rules.ports.defaultPortFrom._ref" |
  "rules.ports.defaultPortFrom._type" |
  "rules.ports.defaultPortFrom._weak" |
  "rules.ports.defaultPortTo" |
  "rules.ports.defaultPortTo._ref" |
  "rules.ports.defaultPortTo._type" |
  "rules.ports.defaultPortTo._weak" |
  "rules.ports.returnPorts" |
  "rules.ports.returnPorts.availablePortsFrom" |
  "rules.ports.returnPorts.availablePortsFrom[]._key" |
  "rules.ports.returnPorts.availablePortsFrom[]._ref" |
  "rules.ports.returnPorts.availablePortsFrom[]._type" |
  "rules.ports.returnPorts.availablePortsFrom[]._weak" |
  "rules.ports.returnPorts.availablePortsTo" |
  "rules.ports.returnPorts.availablePortsTo[]._key" |
  "rules.ports.returnPorts.availablePortsTo[]._ref" |
  "rules.ports.returnPorts.availablePortsTo[]._type" |
  "rules.ports.returnPorts.availablePortsTo[]._weak" |
  "rules.ports.returnPorts.defaultPortFrom" |
  "rules.ports.returnPorts.defaultPortFrom._ref" |
  "rules.ports.returnPorts.defaultPortFrom._type" |
  "rules.ports.returnPorts.defaultPortFrom._weak" |
  "rules.ports.returnPorts.defaultPortTo" |
  "rules.ports.returnPorts.defaultPortTo._ref" |
  "rules.ports.returnPorts.defaultPortTo._type" |
  "rules.ports.returnPorts.defaultPortTo._weak" |
  "rules.productCode" |
  "rules.productCode._ref" |
  "rules.productCode._type" |
  "rules.productCode._weak" |
  "rules.vehicles" |
  "rules.vehicles.bikes" |
  "rules.vehicles.bikes.locked" |
  "rules.vehicles.bikes.value" |
  "rules.vehicles.car" |
  "rules.vehicles.car.locked" |
  "rules.vehicles.car.value" |
  "rules.vehicles.car.vehicleCategories" |
  "rules.vehicles.car.vehicleCategories[]._key" |
  "rules.vehicles.car.vehicleCategories[]._ref" |
  "rules.vehicles.car.vehicleCategories[]._type" |
  "rules.vehicles.car.vehicleCategories[]._weak" |
  "rules.vehicles.motorcycle" |
  "rules.vehicles.motorcycle.locked" |
  "rules.vehicles.motorcycle.value" |
  "rules.vehicles.motorcycle.vehicleCategories" |
  "rules.vehicles.motorcycle.vehicleCategories[]._key" |
  "rules.vehicles.motorcycle.vehicleCategories[]._ref" |
  "rules.vehicles.motorcycle.vehicleCategories[]._type" |
  "rules.vehicles.motorcycle.vehicleCategories[]._weak" |
  "rules.weekdays" |
  "rules.weekdays[]";
